/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cf_vbnm_demo_gateway_Gateway */

#ifndef _Included_cf_vbnm_demo_gateway_Gateway
#define _Included_cf_vbnm_demo_gateway_Gateway
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cf_vbnm_demo_gateway_Gateway
 * Method:    getPacket
 * Signature: (Lcf/vbnm/demo/gateway/PacketHeader;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_cf_vbnm_demo_gateway_Gateway_getPacket
  (JNIEnv *, jobject, jobject);

/*
 * Class:     cf_vbnm_demo_gateway_Gateway
 * Method:    send
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_cf_vbnm_demo_gateway_Gateway_send
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     cf_vbnm_demo_gateway_Gateway
 * Method:    getNetworkInterface
 * Signature: ()[[B
 */
JNIEXPORT jobjectArray JNICALL Java_cf_vbnm_demo_gateway_Gateway_getNetworkInterface
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
